ktor:
  development: true
  deployment:
    port: 8080
    watch:
      - classes
  application:
    modules:
      - com.cloverclient.corp.core.CoreKt.coreModule
      - com.cloverclient.corp.gateway.GatewayKt.gatewayModule

jwt:
  issuer: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_4Wft4FeT2"
  audience: "63208gfven5ue041luetq6sh6m"
  realm: "us-east-1_4Wft4FeT2"

aws:
  region: "__local__"
